system_config:
    time_interval: 0 # unit: hour

telegram_config:
    bot_token : ""
    chat_id : ""

elsevier_config:
    API_key: ""

email_config:
    smtp_server:
    smtp_port: 
    sender: 
    password:
    receiver: 